// Shared mutable app state. Every module that needs to read or reassign one of
// these (not just mutate an array/object in place) must go through this object -
// ES modules only allow live-binding *reads* of another module's `let`, never a
// reassignment from outside the module that declared it. Wrapping everything in
// one object sidesteps that: `state.x = y` is a property write, always legal.
export const state = {
  reqDetails: {},
  reqVisitDetails: {},
  editingRequestId: null,
  finRowDetails: {},
  editingFinanceId: null,
  financeLedger: [],
  nextFinanceId: 1,
  vendorProfiles: [],
  activityLog: [],
  vendRegDetails: {},
  vendRegFiles: {},
  currentVendor: null,
  projects: [],
  dprLog: [],
  teamMembers: [],
  materialLots: [],
  requests: [],
  expanded: {},
  activeTab: 'projects',
  currentUser: null,
  loggedInClient: null,
  projectDocsExpanded: {},
  editingId: null,
  updatingId: null,
  deletingId: null,
  pendingConstraints: [],
  dprPendingConstraints: [],
  pendingMilestones: [],
  currentMilestones: [],
  editingDprId: null,
  currentSnags: [],
  pendingSnagPhotoUrl: '',
  formMilestones: [],
  formVendors: [{name:'',role:''}],
  formProducts: [{name:'',qty:''}],
  formTowers: [{name:''}],
  dprProducts: [],
  nextId: 4,
  nextDprId: 3,
  nextMemberId: 6,
  editingMemberId: null,
  nextRequestId: 1,
  jmrUploadedUrls: [],
  currentChecklist: [],
  premockupChecklistExpanded: {},
  msGanttExpanded: {},
  quickSnagPhotoUrl: '',
  lotItems: [{product:'',bundleCount:0,qtyDispatched:0}],
  lotLrCopyUrl: '',
  editingLotId: null,
  nextLotId: 3,
  dprArrivalGeoLocation: '',
  dprArrivalPhotoUrls: [],
  dprSnagPhotoUrl: '',
  dprWccUrls: [],
  dprChecklistState: {},
  dprPhotoUrls: [],
  dprReportPdfUrl: '',
  requestTimelineExpanded: {},
  ackRequestId: null
};
