import { doClientLogin, clientLogout } from '../auth/clientAuth.js';
import { showTeamLogin, teamLogin, showTeamDashboard, lockTeam, backToClient } from '../auth/teamAuth.js';
import { openVendorRegister, vendorRegister, vendorLogin, vendorLogout } from '../auth/vendorAuth.js';
import { syncProject, loadAllData } from '../data/loadAllData.js';
import { logActivity } from '../lib/activityLog.js';
import { milestoneKeyFor, isChecklistActive, blankChecklistData, checklistTotalItems, checklistDoneItems, getAdminEmail, gmailComposeLink, notifyByGmail, notifyJMRUpload, reqFieldGroup, reqTypeLabel } from '../lib/constants.js';
import { toggleProjectDocs, suggestSnagSeverity, updateSnagSeverityHint, statusBadge, visibleProjects } from '../lib/helpers.js';
import { projectToRow, rowToProject, dprToRow, rowToDpr, memberToRow, rowToMember, lotToRow, rowToLot, requestToRow, rowToRequest, financeRowToRow, rowToFinanceRow } from '../lib/mappers.js';
import { makeMockClient } from '../lib/supabaseClient.js';
import { pickFilesOrWarn, docLink, uploadFiles, uploadFilesWithNames, fileUploadRowHTML } from '../lib/uploads.js';
import { computeAlerts, updateBell, setBadge, updateTabBadges, updateRequestsBadge, buildRequestActivityHTML, buildNotifHTML, quickSolve, goToProject, copyDigest } from '../sections/alerts.js';
import { clientGanttHTML, renderClientPortal, sendClientMsg } from '../sections/clientPortal/clientPortal.js';
import { renderDashboard } from '../sections/dashboard/dashboardTab.js';
import { renderDPR, openAddDPR, openEditDPR, renderDPRForm, dprDayNo, dprDaysLeft, divFmt, renderDPRChecklist, toggleDPRChecklistItem, renderDPRProducts, updateDPRProductDerived, saveDPR } from '../sections/dpr/dprTab.js';
import { approvedVendors, populateFinanceVendorDropdown, openAddFinanceRow, openAddFinanceRowForProject, openEditFinanceRow, onFinanceProjectChange, onFinanceFieldRecalc, recalcFinanceComputed, saveFinanceRow, renderFinance } from '../sections/finance/financeTab.js';
import { renderGantt, renderPipeline } from '../sections/gantt/ganttTab.js';
import { getInstalledForProject, getTotalDispatched, renderMaterial, timelineMetric, renderLotCard, renderLotItems, addLotItemRow, openAddLot, openAddLotForProject, showRemainingToDispatch, openEditLot, saveLot } from '../sections/material/materialTab.js';
import { renderMetrics } from '../sections/metrics.js';
import { showSection, openPanel, closePanel, showClientSection, setTab } from '../sections/navigation.js';
import { renderChecklist, loadChecklistTemplate, addChecklistItem, toggleChecklistItem, removeChecklistItem, renderSnagList, addSnag, cycleSnagStatus, openAddSnagForProject, saveSnagQuick, openAddProject, openEditProject, saveProject, showFormErr, askDelete, confirmDelete, openMilestonesPanel, renderExistingMilestonesStandalone, updateExistingMilestoneStandalone, addMilestoneStandalone, renderPendingMsStandalone, saveMilestonesOnly, openUpdate, addMilestone, renderPendingMs, saveUpdate, addComment } from '../sections/projects/addEditProject.js';
import { onOrderTypeChange, renderFormMilestones, renderExistingMilestones, updateExistingMilestone, addMilestoneToForm, confirmAddMilestoneToForm, renderTowerRows, renderVendorRows, addVendorRow, renderProductQuickPicks, quickAddProduct, renderProductRows, addProductRow, renderConstraintList, addConstraintToForm, removeFormConstraint, addDPRConstraint, removeDPRConstraint, toggleNoConstraints, addUpdateConstraint, cycleConstraintStatus, editConstraintNextAction, renderUpdateConstraints, escalateConstraint, escalateSnag, cycleSnagStatusOnProject } from '../sections/projects/formHelpers.js';
import { renderProjects, toggleChecklistDropdown, renderChecklistDropdown, renderAllChecklistDropdowns, acknowledgeChecklist, renderCard, toggleCard, renderDetail } from '../sections/projects/projectCards.js';
import { fieldRowHTML, captureDPRArrivalGeoLocation, captureGeoLocation, reqFieldChanged, renderRequestFields, openAddRequest, openEditRequest, genRequestNumber, saveRequest, notifyProjectTeamNewRequest, notifyNewRequest, renderRequests, sendVisitReportEmail, tatBadge, reviewWaitBadge, toggleRequestTimeline, fmtDateTime, slaGap, renderRequestStageTimeline, renderRequestCard, viewRequestReadOnly, updateRequestFields, acknowledgeRequest, confirmAcknowledge, sendAssignmentEmails, changePlannedDate, advanceRequestStatus, convertRequestToProject, confirmConvertRequestToProject, exportProjectsCSV, parseCSV, importProjectsCSV, exportRequestsCSV } from '../sections/requests/requestsTab.js';
import { renderTeamMgmt, togglePerm, openAddMember, openEditMember, updateRolePreview, saveMember, toggleMemberStatus, deleteMember } from '../sections/team/teamMgmtTab.js';
import { renderVendorPortal } from '../sections/vendorPortal/vendorPortal.js';
import { updateNewVendorBadge, renderNewVendors, markVendorReviewed, markVendorApprovedByShashank } from '../sections/vendors/newVendorsTab.js';

// Every function invoked from an inline onclick="..." attribute in index.html needs to
// be reachable on window - once this app moved into ES modules those functions stopped
// being implicit globals. This is the single place that re-exposes all of them.
export function installDomGlobals(){
  Object.assign(window, {
    doClientLogin,
    clientLogout,
    showTeamLogin,
    teamLogin,
    showTeamDashboard,
    lockTeam,
    backToClient,
    openVendorRegister,
    vendorRegister,
    vendorLogin,
    vendorLogout,
    syncProject,
    loadAllData,
    logActivity,
    milestoneKeyFor,
    isChecklistActive,
    blankChecklistData,
    checklistTotalItems,
    checklistDoneItems,
    getAdminEmail,
    gmailComposeLink,
    notifyByGmail,
    notifyJMRUpload,
    reqFieldGroup,
    reqTypeLabel,
    toggleProjectDocs,
    suggestSnagSeverity,
    updateSnagSeverityHint,
    statusBadge,
    visibleProjects,
    projectToRow,
    rowToProject,
    dprToRow,
    rowToDpr,
    memberToRow,
    rowToMember,
    lotToRow,
    rowToLot,
    requestToRow,
    rowToRequest,
    financeRowToRow,
    rowToFinanceRow,
    makeMockClient,
    pickFilesOrWarn,
    docLink,
    uploadFiles,
    uploadFilesWithNames,
    fileUploadRowHTML,
    computeAlerts,
    updateBell,
    setBadge,
    updateTabBadges,
    updateRequestsBadge,
    buildRequestActivityHTML,
    buildNotifHTML,
    quickSolve,
    goToProject,
    copyDigest,
    clientGanttHTML,
    renderClientPortal,
    sendClientMsg,
    renderDashboard,
    renderDPR,
    openAddDPR,
    openEditDPR,
    renderDPRForm,
    dprDayNo,
    dprDaysLeft,
    divFmt,
    renderDPRChecklist,
    toggleDPRChecklistItem,
    renderDPRProducts,
    updateDPRProductDerived,
    saveDPR,
    approvedVendors,
    populateFinanceVendorDropdown,
    openAddFinanceRow,
    openAddFinanceRowForProject,
    openEditFinanceRow,
    onFinanceProjectChange,
    onFinanceFieldRecalc,
    recalcFinanceComputed,
    saveFinanceRow,
    renderFinance,
    renderGantt,
    renderPipeline,
    getInstalledForProject,
    getTotalDispatched,
    renderMaterial,
    timelineMetric,
    renderLotCard,
    renderLotItems,
    addLotItemRow,
    openAddLot,
    openAddLotForProject,
    showRemainingToDispatch,
    openEditLot,
    saveLot,
    renderMetrics,
    showSection,
    openPanel,
    closePanel,
    showClientSection,
    setTab,
    renderChecklist,
    loadChecklistTemplate,
    addChecklistItem,
    toggleChecklistItem,
    removeChecklistItem,
    renderSnagList,
    addSnag,
    cycleSnagStatus,
    openAddSnagForProject,
    saveSnagQuick,
    openAddProject,
    openEditProject,
    saveProject,
    showFormErr,
    askDelete,
    confirmDelete,
    openMilestonesPanel,
    renderExistingMilestonesStandalone,
    updateExistingMilestoneStandalone,
    addMilestoneStandalone,
    renderPendingMsStandalone,
    saveMilestonesOnly,
    openUpdate,
    addMilestone,
    renderPendingMs,
    saveUpdate,
    addComment,
    onOrderTypeChange,
    renderFormMilestones,
    renderExistingMilestones,
    updateExistingMilestone,
    addMilestoneToForm,
    confirmAddMilestoneToForm,
    renderTowerRows,
    renderVendorRows,
    addVendorRow,
    renderProductQuickPicks,
    quickAddProduct,
    renderProductRows,
    addProductRow,
    renderConstraintList,
    addConstraintToForm,
    removeFormConstraint,
    addDPRConstraint,
    removeDPRConstraint,
    toggleNoConstraints,
    addUpdateConstraint,
    cycleConstraintStatus,
    editConstraintNextAction,
    renderUpdateConstraints,
    escalateConstraint,
    escalateSnag,
    cycleSnagStatusOnProject,
    renderProjects,
    toggleChecklistDropdown,
    renderChecklistDropdown,
    renderAllChecklistDropdowns,
    acknowledgeChecklist,
    renderCard,
    toggleCard,
    renderDetail,
    fieldRowHTML,
    captureDPRArrivalGeoLocation,
    captureGeoLocation,
    reqFieldChanged,
    renderRequestFields,
    openAddRequest,
    openEditRequest,
    genRequestNumber,
    saveRequest,
    notifyProjectTeamNewRequest,
    notifyNewRequest,
    renderRequests,
    sendVisitReportEmail,
    tatBadge,
    reviewWaitBadge,
    toggleRequestTimeline,
    fmtDateTime,
    slaGap,
    renderRequestStageTimeline,
    renderRequestCard,
    viewRequestReadOnly,
    updateRequestFields,
    acknowledgeRequest,
    confirmAcknowledge,
    sendAssignmentEmails,
    changePlannedDate,
    advanceRequestStatus,
    convertRequestToProject,
    confirmConvertRequestToProject,
    exportProjectsCSV,
    parseCSV,
    importProjectsCSV,
    exportRequestsCSV,
    renderTeamMgmt,
    togglePerm,
    openAddMember,
    openEditMember,
    updateRolePreview,
    saveMember,
    toggleMemberStatus,
    deleteMember,
    renderVendorPortal,
    updateNewVendorBadge,
    renderNewVendors,
    markVendorReviewed,
    markVendorApprovedByShashank
  });
}
