-- Phase B baseline schema. Mechanical transcription of the columns actually read/written by
-- src/lib/mappers.js (the "SUPABASE SYNC LAYER") plus src/lib/activityLog.js and
-- src/auth/vendorAuth.js. No RLS yet (Phase D) and no auth hardening yet (Phase C) — this
-- migration only makes the 8 tables exist so TEST_MODE=false can round-trip real data.
--
-- id columns: every row this app inserts already carries an explicit client-computed integer
-- id (state.nextId = max(existing ids)+1, see src/data/loadAllData.js) except vendor_profiles
-- (keyed by auth user id) and activity_log (never read back by id). "generated by default as
-- identity" (not "always") so those explicit inserts keep working without OVERRIDING SYSTEM VALUE.
--
-- The architecture doc proposed making dpr_log.date and team_members.last_login real
-- date/timestamptz columns, on the assumption that src/lib/helpers.js's fmtDate() re-formats
-- them on render either way, making the internal storage change invisible. Verified against
-- the actual render call sites and that assumption was WRONG: dprTab.js:62 prints `d.date` raw
-- (no fmtDate), and teamMgmtTab.js:37 prints `m.lastLogin` raw too — a real date/timestamptz
-- column would show as ISO ("2026-06-16") instead of the original display string ("16 Jun
-- 2026"), a visible regression. Worse, teamMgmtTab.js:119 sets a brand-new member's lastLogin
-- to the literal string 'Never', which a timestamptz column would reject outright and break
-- "Add Team Member". Both columns are kept as `text` here — exact pass-through, zero app-code
-- changes, zero visible difference from today.

create table if not exists projects (
  id integer generated by default as identity primary key,
  access_code text,
  created_by text,
  name text,
  tower text,
  developer text,
  city text,
  state text,
  supervisor text,
  vendor text,
  supervisor_wa text,
  status text,
  planned_qty integer,
  installed_qty integer,
  ra_bill_qty integer,
  ra_bill_amt numeric,
  payment_collected numeric,
  jmr_qty integer,
  constraints_open integer,
  ra_bill_ready boolean,
  start_date date,
  committed_date date,
  actual_date date,
  drive_link text,
  unit text,
  order_type text,
  vendors jsonb default '[]'::jsonb,
  products jsonb default '[]'::jsonb,
  constraints jsonb default '[]'::jsonb,
  milestones jsonb default '[]'::jsonb,
  comments jsonb default '[]'::jsonb,
  po_qty integer default 0,
  so_qty integer default 0,
  ra_bill_history jsonb default '[]'::jsonb,
  jmr_docs jsonb default '[]'::jsonb,
  checklist jsonb default '[]'::jsonb,
  snags jsonb default '[]'::jsonb,
  sales_person_name text default '',
  source_request_type text default '',
  sales_person_email text default '',
  framing_material text default '',
  section_size text default '',
  premockup_checklist jsonb,
  premockup_checklist_completed_at timestamptz,
  premockup_checklist_reviewed boolean default false,
  finance_last_reviewed_jmr numeric default 0,
  mockup_checklist jsonb,
  mockup_checklist_completed_at timestamptz,
  mockup_checklist_reviewed boolean default false,
  pre_main_survey_checklist jsonb,
  pre_main_survey_checklist_completed_at timestamptz,
  pre_main_survey_checklist_reviewed boolean default false,
  handover_checklist jsonb,
  handover_checklist_completed_at timestamptz,
  handover_checklist_reviewed boolean default false,
  work_policy_checklist jsonb,
  work_policy_checklist_completed_at timestamptz,
  work_policy_checklist_reviewed boolean default false,
  po_date date,
  days_available integer,
  material_first_lot_date date,
  install_commencement_date date,
  wcc_docs jsonb default '[]'::jsonb,
  ra_bill_docs jsonb default '[]'::jsonb,
  project_docs jsonb default '[]'::jsonb
);

create table if not exists dpr_log (
  id integer generated by default as identity primary key,
  proj_id integer references projects(id),
  project text,
  date text,
  supervisor text,
  day_no integer,
  days_left integer,
  committed_mp integer,
  actual_mp integer,
  manpower integer,
  photos integer,
  products jsonb default '[]'::jsonb,
  constraints jsonb default '[]'::jsonb,
  action_taken text,
  remarks text,
  internal_hindrance text,
  next_dispatch text,
  escalations text,
  next text,
  framing_material text default '',
  section_size text default '',
  photo_urls jsonb default '[]'::jsonb,
  report_pdf_url text default ''
);

create table if not exists team_members (
  id integer generated by default as identity primary key,
  name text,
  username text,
  pin text,
  role text,
  dept text,
  wa text,
  active boolean default true,
  last_login text,
  email text default ''
);

create table if not exists material_lots (
  id integer generated by default as identity primary key,
  proj_id integer references projects(id),
  lot_no text,
  dispatch_date date,
  expected_arrival date,
  actual_arrival date,
  vehicle text,
  driver text,
  dispatch_notes text,
  condition text,
  bundle_matched text,
  storage text,
  arrival_notes text,
  items jsonb default '[]'::jsonb,
  arrival_acked_at timestamptz,
  arrival_geo_location text,
  arrival_photo_urls jsonb default '[]'::jsonb,
  lr_copy_url text
);

create table if not exists requests (
  id integer generated by default as identity primary key,
  request_number text,
  request_type text,
  request_sub_type text,
  status text,
  created_by text,
  assigned_supervisor text,
  planned_visit_date date,
  actual_visit_date date,
  planned_date_locked boolean default false,
  details jsonb default '{}'::jsonb,
  checklist jsonb default '[]'::jsonb,
  linked_project_id integer references projects(id),
  created_at timestamptz default now(),
  reviewed_at timestamptz,
  converted_at timestamptz
);

create table if not exists finance_ledger (
  id integer generated by default as identity primary key,
  proj_id integer references projects(id),
  product text,
  description text,
  location text,
  boq_qty integer default 0,
  contractor text,
  wo_qty integer default 0,
  wo_rate numeric default 0,
  contract_value numeric default 0,
  payment_given numeric default 0,
  retention numeric default 0,
  work_status text,
  installation_payment_due numeric default 0,
  payment_pending numeric default 0,
  installation_amount_pending text default '',
  ra_bill_status text,
  ra_bill_due_date date,
  ra_bill_due_amount numeric default 0,
  ra_bill_balance numeric default 0,
  billed_qty integer default 0,
  billed_amt numeric default 0,
  unbilled_qty integer default 0,
  unbilled_amt numeric default 0,
  installation_rate numeric default 0,
  due_billing numeric default 0,
  hold_amount numeric default 0
);

create table if not exists vendor_profiles (
  user_id uuid primary key references auth.users(id),
  email text,
  company_name text default '',
  trade_name text default '',
  constitution text default '',
  vendor_type text default '',
  phone text default '',
  gstin text default '',
  registered_address text default '',
  pan_number text default '',
  pan_name text default '',
  last_year_turnover text default '',
  main_items text default '',
  credit_term text default '',
  bank_name text default '',
  account_no text default '',
  ifsc_code text default '',
  msme_doc_url text default '',
  gst_doc_url text default '',
  pan_doc_url text default '',
  tan_doc_url text default '',
  cheque_doc_url text default '',
  scope_of_work text default '',
  reviewed_by_admin boolean default false,
  approved_by_shashank boolean default false,
  created_at timestamptz default now()
);

create table if not exists activity_log (
  id bigint generated always as identity primary key,
  event_type text,
  message text,
  created_at timestamptz default now()
);

create index if not exists idx_dpr_log_proj_id on dpr_log(proj_id);
create index if not exists idx_material_lots_proj_id on material_lots(proj_id);
create index if not exists idx_finance_ledger_proj_id on finance_ledger(proj_id);
create index if not exists idx_requests_linked_project_id on requests(linked_project_id);
